import { jakarta } from '@/utils/fonts'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className="antialiased">
      <body className={jakarta.className}>
        <div className="min-h-screen">{children}</div>
      </body>
    </html>
  )
}
